export const SET_USER = 'SET_USER';
export const SET_SETTINGS = 'SET_SETTINGS';

export const SET_ERRORS = 'SET_ERRORS';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_STATUS_GLOBAL = 'SET_STATUS_GLOBAL';

export const SET_BOT_LIST = 'SET_BOT_LIST';
export const DELETE_BOT_FROM_LIST = 'DELETE_BOT_FROM_LIST';
export const SET_BOT_FOR_EDIT = 'SET_BOT_FOR_EDIT';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGES_FROM_SERVER = 'SET_MESSAGES_FROM_SERVER';
export const CLEAN_MESSAGES = 'CLEAR_MESSAGES';
export const SHOW_ADD_ORDER_WINDOW_BOT = 'SHOW_ADD_ORDER_WINDOW_BOT';

export const SET_SERVICES_LIST = 'SET_SERVICES_LIST';
export const DELETE_SERVICE_FROM_LIST = 'DELETE_SERVICE_FROM_LIST';
export const SET_SERVICE_FOR_EDIT = 'SET_SERVICE_FOR_EDIT';
export const SHOW_ADD_SERVICE_WINDOW = 'SHOW_ADD_SERVICE_WINDOW';

export const SET_POSITIONS_LIST = 'SET_POSITIONS_LIST';
export const DELETE_POSITION_FROM_LIST = 'DELETE_POSITION_FROM_LIST';
export const SET_POSITION_FOR_EDIT = 'SET_POSITION_FOR_EDIT';

export const SET_EMPLOYEES_LIST = 'SET_EMPLOYEES_LIST';
export const DELETE_EMPLOYEE_FROM_LIST = 'DELETE_EMPLOYEE_FROM_LIST';
export const SET_EMPLOYEE_FOR_EDIT = 'SET_EMPLOYEE_FOR_EDIT';
export const SHOW_ADD_EMPLOYEE_WINDOW = 'SHOW_ADD_EMPLOYEE_WINDOW';

export const SET_ORDERS_LIST = 'SET_ORDERS_LIST';
export const DELETE_ORDER_FROM_LIST = 'DELETE_ORDER_FROM_LIST';
export const SET_ORDER_FOR_EDIT = 'SET_ORDER_FOR_EDIT';
export const SHOW_ADD_ORDER_WINDOW = 'SHOW_ADD_ORDER_WINDOW';
export const SET_ORDER_TIME = 'SET_ORDER_TIME';
export const SET_ORDER_DATE = 'SET_ORDER_DATE';

export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const DELETE_CATEGORY_FROM_LIST = 'DELETE__CATEGORY_FROM_LIST';
export const SET_CATEGORY_FOR_EDIT = 'SET_CATEGORY_FOR_EDIT';
export const SHOW_ADD_CATEGORY_WINDOW = 'SHOW_ADD_CATEGORY_WINDOW';

export const SET_USERS_ADMIN = 'SET_USERS_ADMIN';
export const DELETE_USER_ADMIN = 'DELETE_USER_ADMIN';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_MONEY = 'SET_MONEY';


